name = "rolldorado-bonus-ch"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-bonus.ch"
HMAC_KEY = "937e21463cbe8c7b4969dc5ce1d2a1e890bd6eba1595b04f87ec5d634cee2f53"
COOKIE_NAME = "1j3"
PLAY_PATH = "play"
BUTTON_ID = "p8b6e035c6822d368d3acaa7f88a118d5"
GATE_SALT = "c74ced6a53a1dc3a"
